version: '3.1'

services:

    consignment-cli:
        build: ./consignment-cli
        environment:
          MICRO_REGISTRY: "mdns"

    user-cli:
        build:  ./user-cli
        environment:
          MICRO_REGISTRY: "mdns"
                
    consignment-service:
        build: ./consignment-service
        ports:
          - 8787:50051
        environment: 
          MICOR_REGISTRY: "mdns"
          MICRO_ADDRESS: ":50051"
          DB_HOST: "datastore:27017"

    vessel-service:
        build: ./vessel-service
        ports:
          - 8686:50051
        environment:
          MICRO_REGISTRY: "mdns"
          MICRO_ADDRESS: ":50051"
          DB_HOST: "datastore:27017"

    user-service:
        build: ./user-service
        ports:
          - 8585:50051
        environment:
          MICRO_REGISTRY: "mdns"
          MICRO_ADDRESS: ":50051"


    datastore:
      image: mongo
      ports:
        - 27017:27017      
     
    database:
      image: postgres
      ports:
        - 5432:5432


